### PR TITLE
Fix modules styling #135

### PR DESCRIPTION
**Pull request by mokalebo**
Modifying module boxes to prevent extension below the underline.
Dropdown arrow larger and more visible.
Changing module division to be dynamic depending on number of modules selected.

### CODE REVIEW

**Comment by djw8605** [comment]
@mokalebo why did you close this?

**Comment by mokalebo** [comment]
I thought i used the wrong procedure for a pull request. I will reopen it.

**Comment by djw8605** [comment]
It looks like when I click on the modules, some styling is weird.

**Comment by mokalebo** [comment]
What does it look like when you click on the modules?

**Comment by djw8605** [comment]
When I select one of the modules by clicking on it, all the styling is lost, it appears.

image

**Pull request merged**
