### PR TITLE
Add checking for writeability and visualizization

### PR DESCRIPTION
**Pull request by djw8605**
Adds a new directive, remoteWritable, which can be used on
form elements to check if the remote directory is writable.

The test is conducted through creating or opening a new file
in the dirname of the path.  If it is successful, it is assumed
that the file will be writable as well.

### CODE REVIEW

**Comment by djw8605** [comment]
This addresses #34

**Comment by djw8605** [comment]
@robogen could you take a look at this pull request.

**Comment by robogen** [comment]
Taking a quick look at it, there's a typo on line 182 of jobSubmissionCtrl.js for the Error statement. Otherwise, I'm seeing a "Got error from checking writability: Error: No such file". Not sure where that's coming from in the checkWritable function, but checking into that now.

**Comment by djw8605** [comment]
That error: `Got error from checking writability: Error: No such file` could come if the directory is truly not writable.  I mean, does the path make sense?

**Comment by robogen** [comment]
Yea, the path looks fine. If I erase a character and then re-add the same character the verification comes back fine. It seems to be happening on page load with whatever default value is there, but sometimes it does it on the .slurm line and sometimes the .error line

**Comment by djw8605** [comment]
Hum. Did you pull the most recent updates. There was a problem like that, but I though I fixed it. 

-Derek

**Comment by robogen** [comment]
Yes, it's the most up-to-date. This is the error I'm seeing, this is the first page load and it gives this verification error. Deleting a character and readding it to force a new check gives a 'valid' response.

onload

**Comment by djw8605** [comment]
Hum… I could have sworn I fixed this.  Where is the error coming from?  The delete?

-Derek

**Comment by robogen** [comment]
I think so, with the debugging I've been doing this is what I'm seeing

pre

**Comment by djw8605** [comment]
Ok, I think I figured it out in f7202e3.  Apparently you have to use the keyword `var` for the variables to be unique between async callbacks.  Odd...

**Comment by robogen** [comment]
Huh, yea that is kind of odd. But I grabbed your latest commit and yea, that seems to be working. Not seeing it claim it can't work on page load now.

**Pull request merged**
