### PR TITLE
Added tooltips to the job submission form for clarity

### PR DESCRIPTION
**Pull request by adamfitzgibbon**
Additionally, bootstrap tooltips can now be enabled and used on any other page.

### CODE REVIEW

**Comment by adamfitzgibbon** [comment]
Addresses #63

**Comment by djw8605** [comment]
What's `tether.js` used for?  Also, could you try to use bower for client side javascript components rather than npm?

**Comment by adamfitzgibbon** [comment]
It's a library that boostrap needs for its tooltip plugin. It helps keep absolutely positioned elements linked to other elements. Yeah I can make that change.

**Comment by djw8605** [comment]
Could you attach a screenshot of the tooltip?

**Comment by adamfitzgibbon** [comment]
Sure. It looks slightly better on the bootstrap site (it has a little tail pointing to the element it's attached to), so there might be some sort of stylesheet conflict or something that is causing it to look a little different, but it still looks ok to me.screen shot 2016-12-08 at 2 43 28 pm

**Comment by djw8605** [comment]
Could you add the tooltip to the left, so it's right next to the text or title of the input.

**Comment by adamfitzgibbon** [comment]
So right after the label is where it should be positioned?

**Comment by djw8605** [comment]
Yeah. Also, I don't think it needs it's own column.  It should probably just have a single space between the label and the tooltip 'i'

**Comment by adamfitzgibbon** [comment]
screen shot 2016-12-08 at 2 54 43 pm

**Comment by adamfitzgibbon** [comment]
Awesome. Merging that in and closing the issue.

**Pull request merged**
