### PR TITLE
Added labels to Gauges

### PR DESCRIPTION
**Pull request by adamfitzgibbon**
screen shot 2016-01-22 at 2 37 09 pm

Added the labels as headers above the gauges, addressing issue #12

### CODE REVIEW

**Comment by djw8605** [comment]
Could you add a separator between the two charts?  Maybe a horizontal rule?

Also, could you add the titles for the graphs to the *.html file, rather than prepending them with angular?

**Comment by adamfitzgibbon** [comment]
I had originally added them to the html, but then they are loaded before the gauges and it looks pretty bad because the way I had to set the margin makes them overlap when the gauges haven't loaded yet. I can put them back into the html if that isn't an issue though.
screen shot 2016-01-22 at 3 51 25 pm

I added just a default horizontal rule. Is that enough or should it be more definitive?

**Comment by djw8605** [comment]
The horizontal looks ok.  I wonder, could one draw the graphs, but just have the text be "loading".  To the graph is there, but instead of "gigabytes", it says "Loading..."?  And when you have the data, just remove the old graphs, and replace with the updated ones?

**Comment by adamfitzgibbon** [comment]
Would it work if I just copied the graphs to outside of the function and replaced the data inputs with those placeholders?

**Comment by djw8605** [comment]
Yeah, probably.  Test it!

**Comment by adamfitzgibbon** [comment]
Yeah that seems to work pretty smoothly. I put the labels in the html and it's much less visually jarring for the graphs to already be on the page when they are populated.

**Pull request merged**
