### PR TITLE
Adding tutorials to HCCGo

### LINKED ISSUE #243: New Tutorials
Please add the following tutorial repos to HCCGo. It would be excellent if we could get these in before the 4/21

https://github.com/unlhcc/matlab-tutorial
https://github.com/unlhcc/python-tutorial
https://github.com/unlhcc/mathematica-tutorial
https://github.com/unlhcc/blast-tutorial

### PR DESCRIPTION
**Pull request by djw8605**
@CarrieBrown take a look at this.  Here is a link to a Mac build version with the new tutorials: https://unl.box.com/s/0cxr8b1287gkx7qlpo6oxrfvots1mxst

This fixes #243

### CODE REVIEW

**Comment by CarrieBrown** [comment]
The MATLAB tutorial loads the submit files but does not clone the files.

**Comment by djw8605** [comment]
Yup, it was a typo, my bad.  Change is 18376c1.  Here is a new build: https://unl.box.com/s/4jttgz20ve6r7c1pwn32q3glv281ch2w

**Comment by CarrieBrown** [comment]
Rest of the tutorials work great! Thanks!

Last tutorial to add: https://github.com/unlhcc/blast-watermelon
I will update this repo as I finish building the necessary files.

**Comment by djw8605** [comment]
Sure, I added the last tutorial in d9c9d00, new build is here: https://unl.box.com/s/1dneumbrz184j16y38jit6ysbpopt4lw

**Pull request merged**
