### PR TITLE
Added a loading bar. Need to determine where DUO is happening.

### PR DESCRIPTION
**Pull request by caseylargent**
Added a loading bar to the welcome page. May need to mess with CSS to look more appealing. I also need to determine where the DUO authentication is happening to place another percentage gain there.

### CODE REVIEW

**Comment by djw8605** [comment]
Yeah, it's pushing the debug screen down.  Could you put the progress bar inside the login area?  Maybe just below the submit button.

DUO is happening around the function `userPrompt`: https://github.com/unlhcc/HCCGo/blob/master/HCCGo/app/js/WelcomeCtrl.js#L93

You should also add some progress to 
https://github.com/unlhcc/HCCGo/blob/master/HCCGo/app/js/WelcomeCtrl.js#L110

**Comment by djw8605** [comment]
can you modify the debug screen below to fit within the screen better.

**Comment by caseylargent** [comment]
image

**Comment by caseylargent** [comment]
This one is 20em for the height. (What it currently is now)
image

**Comment by djw8605** [comment]
This is how it looks on my screen, with no changes:
image

**Pull request closed without merging**
