### PR TITLE
set default for location, output, and error to '/work/'

### PR DESCRIPTION
**Pull request by adamfitzgibbon**
Addressed issue #13 by binding the text fields with '/work/' instead of using a placeholder. 
screen shot 2016-01-26 at 4 16 44 pm

### CODE REVIEW

**Comment by djw8605** [comment]
Can you issue a command to the cluster in order to gather the value of $WORK, then propagate that value into the text box?

**Comment by adamfitzgibbon** [comment]
I have to get to a class, but I'll make those changes along with the job history enhancement tomorrow, as it didn't seem to like my initial try at filling it in from the value returned by the command.

**Comment by adamfitzgibbon** [comment]
screen shot 2016-01-27 at 3 30 01 pm

I got the form to populate with the full $WORK path. You can visually see it getting loaded in, but I suppose there's not much to be done about that because of the time it takes to get the output of the command.

**Comment by djw8605** [comment]
Could you refactor to remove the function from the Connection service, and instead create the function in the job controller, and use the `runCommand` function.

**Comment by djw8605** [comment]
Also, could you display something like "loading work folder" while the command is running?

**Comment by adamfitzgibbon** [comment]
Yeah, how does that look?

**Comment by djw8605** [comment]
What is this job history.json file?

**Comment by adamfitzgibbon** [comment]
Oh I probably should have held off on committing that. That was the default json file I was going to use for saving and loading a job, which hasn't been implemented yet.

**Comment by djw8605** [comment]
go ahead and remove it from this pull request so we can have a proper history.

BTW, you should be working with branches, so things like this don't come up.

**Comment by adamfitzgibbon** [comment]
So do I need to actually remove the file from history, or can I remove the file temporarily and re-commit?

**Comment by djw8605** [comment]
Just introduce a new commit that removes the file will be good enough.

**Pull request merged**
