### PR TITLE
Navbar

### PR DESCRIPTION
**Pull request by robogen**
hccgo_navbar

This pull will bring the navbar feature into HCCGo. Part of this takes old navbar logic out of the controllers of current pages. 

With this change the style and layout of the navbar, controlled from navbar.html, is shared across all pages except the first welcome page. Functionality is controlled in navbar.js

### CODE REVIEW

**Comment by djw8605** [comment]
Can you make the file transfer not be a dropdown, and instead make it another button like "Submit".

**Comment by robogen** [comment]
hccgo_buttons

Easy enough, the dropdown was a remnant of when I was doing uploading and downloading in two seperate pages. Here is what it looks like now. Not sure how I like how big the button becomes, compared to submit. May need to add a little spacing between them as well.

**Comment by djw8605** [comment]
Could we make the buttons different colors?

**Comment by robogen** [comment]
Sure, at the moment they're just using whatever colors bootstrap defaults too. What colors do you think we should use? I might like to leave the 'Submit' button green (for 'go') but maybe make it a lighter green, but what about File Management? Grey you think?

**Comment by djw8605** [comment]
There’s a bunch of different button types other than btn-primary.  Maybe.   btn-secondary?

-Derek

**Comment by robogen** [comment]
hccgo_buttons

Ah, forgot about those, I see what you mean! Here, how's this look? I gave submit 'btn-sucess' and file management 'btn-info'.

**Comment by djw8605** [comment]
Ok, so is this done?

**Comment by robogen** [comment]
yep, for now this should be good

**Pull request merged**
