### PR TITLE
Added icons to application and notifications

### PR DESCRIPTION
**Pull request by adamfitzgibbon**
Added a folder with the icon files. Application icon and some notifications were updated to use the new icon.

### CODE REVIEW

**Comment by djw8605** [comment]
I asked the designer for the source photoshop files so we could include those in the source as well.  I'll attach it here when I get them.

But, I tested this change, and it all looks good.  Seems to work on my Mac.

Is there anywhere else we want to include this Icon?  Maybe in the "brand" of the navigation bar (top left?)

**Comment by djw8605** [comment]
Add the uncompressed Adobe Illustrator file attached here.  Just in case we need to update it some time in the future.

[1608 HCCGo Desktop Icon_FINAL.ai.zip](https://github.com/unlhcc/HCCGo/files/452473/1608.HCCGo.Desktop.Icon_FINAL.ai.zip)

**Comment by adamfitzgibbon** [comment]
Yeah I can try and put that in the navbar, I think that'd be a good place to stick it.

**Comment by adamfitzgibbon** [comment]
Okay I added the icon to the navbar in place of where HCCGo was. I figured that it wasn't needed since it also displays the name at the top of the window. Also fixed some things on the navbar so that one smaller windows it correctly turns into a collapsible. And finally a new folder was added to the root directory to hold the source file for the icon and any other resources we might want to include in the future.

**Comment by djw8605** [comment]
All looks good to me!

Fixes #43

**Pull request merged**
