### PR TITLE
Navbar username 'blinking'

### PR DESCRIPTION
**Pull request by robogen**
This pull should fix the issue where the username blinks as you navigate around. Before, the username would disappear because it would make a new call to the server everytime the navbar got called as an included page. This fix is that after the first time the 'getUsername()' function gets called, the string gets stored in [$templateCache](https://docs.angularjs.org/api/ng/service/$templateCache), a caching mechanism for angularjs.

### CODE REVIEW

**Comment by djw8605** [comment]
Seems ok.  But what if we want to put other values in there?  Like, currently running jobs... things like that.

Would it be better to move the nav bar outside of the ng-view top level element?

**Comment by robogen** [comment]
I tried that, keeping in mind the 'welcome' screen where you login for the first time since it technically has its own navbar. When the navbar gets loaded, the code only gets executed once. There's a few different options available in angularjs for triggering events in a static page ($viewContentLoaded is one of them, an event that fires when ngView gets modified) and I tried using that so that the 'get username' code would only run after a login has occured based on url, but for some reason I couldn't ever get the event to actually fire so the desired behaviour never occurred.

I spent a day or two on getting that working, finally settling on this since it actually worked. If however the desire is to keep relevent job status available on screen I can give it another try, but I think putting it in the navbar is a bit much since we already have the side bar that holds that data. Why not persist that and change the other area? For example: 
hccgo_example


What I mean is, given the picture above, let's persist the blue area to remain displayed on each page. We would have to do something about the half-circle graphics so they aren't so wide. But at the same time we make the purple area variable, so navigating to a different page instead changes that window display. Our controls so far (file management, job submission, etc) take a lot of width which results in unused white space, and the width isn't even necessarily required. If you'd like that sort of data to remain visible, let's just change it up so that (what I'll call a 'data bar', the blue area) will remain persistent on screen. and the (what I'll call the 'cluster view', the purple area) will change dependent on what control is desired by the user.

What do you think?

**Comment by djw8605** [comment]
No, I think how we have it now is good, the blue and purple area should be replaced with each view change.

As for the header, can't you just store the username in the $rootScope, then have a ng-hide or whatever on if $rootScope.username is defined?

**Comment by robogen** [comment]
I'm going to close this pull request for now, I'm working on a new method to accomplish the same goal that's pretty close to your $rootScope suggestion.

**Pull request closed without merging**
