### PR TITLE
Show alert for overwriting files

### PR DESCRIPTION
**Pull request by cjkeilig**
In response to [#159](https://github.com/unlhcc/HCCGo/issues/159)

### CODE REVIEW

**Comment by djw8605** [comment]
@robogen could you review this.

**Comment by djw8605** [comment]
@cjkeilig A ton changed in Jerrod's new pull request #187 .  It may change where a lot of your code needs to go. 😦

**Comment by robogen** [comment]
@cjkeilig sorry about that! once the pull is merged, the changes you'll need to make should be minimal

**Comment by cjkeilig** [comment]
No problem, I need to fix an issue with this anyway. I will pull Jerrod's changes and then integrate what I had.

**Comment by robogen** [comment]
@cjkeilig The pull has been merged, could you take another look at this?

**Comment by cjkeilig** [comment]
Okay, I don't think I should have resolved the conflict, let me know what I need to do.

**Comment by djw8605** [comment]
All I have to say is WTF 😄 .  I would close this pull request and start over.  Weird things happened.

**Comment by cjkeilig** [comment]
Haha okay, I'll do it from master branch

**Comment by cjkeilig** [comment]
@robogen I made a new request called 'File management details'. Looks like this one messed up when I merged with all the updates

**Comment by cjkeilig** [comment]
New pull --> [#189](https://github.com/unlhcc/HCCGo/pull/189)

**Pull request closed without merging**
