### PR TITLE
Add copy/paste functionality.

### PR DESCRIPTION
**Pull request by djw8605**
Add menu items for copy/paste.  @robogen can you test this change on Windows and Linux?

### CODE REVIEW

**Comment by djw8605** [comment]
Fixes #64

**Comment by robogen** [comment]
On both Linux and Windows, key commands like Ctrl+C and Ctrl+V  are working fine, but if I try to use only the menu items to copy or paste it doesn't work.

**Comment by djw8605** [comment]
That's weird. Anything interesting in the debug?  It should be tied to the same code, keys and menu items. 

-Derek

**Comment by robogen** [comment]
Nah, far as the debug no errors are being generated. I'm looking into the Menu documentation to see if Linux/Windows is unique for some reason

**Comment by djw8605** [comment]
As normal, it works for me 😄   I just check in Mac, key bindings and menu items both work.

**Comment by robogen** [comment]
Fixed it! Looking at the documentation at http://electron.atom.io/docs/api/menu/ there's an extra property for submenus called 'role'. I added those to the respective entries in the template and then both key and menu methods started working.

**Comment by djw8605** [comment]
Great!  Can you open a pull request against my pull request?

-Derek

**Comment by djw8605** [comment]
@robogen I added a new commit, bc3307f, that adds some roles.  Is that enough?

**Comment by robogen** [comment]
Yep, that looks fine, it's exactly how my code looks like

**Pull request merged**
