### PR TITLE
Windows Fixes

### PR DESCRIPTION
**Pull request by djw8605**
A set of fixes discovered while testing on windows.

### CODE REVIEW

**Comment by djw8605** [comment]
@robogen could you test this Windows fix.

**Comment by djw8605** [comment]
@robogen you will have to delete your job DBs in the <username>/AppData/Roaming/HCCGo/*.db file.

**Comment by robogen** [comment]
For the updates themselves they seem to be working fine, though I've noticed an error message of "Received updater-error event: Can not find Squirrel" in the dev tools console. Also, I did not have a default job template in Job History

**Comment by djw8605** [comment]
Yeah, the squirrel is a symptom of the updater not working in Windows yet.

**Comment by djw8605** [comment]
Also, I've opened an issue for the job template in the job history: #149

**Pull request merged**
