### PR TITLE
Adds beta notifications

### PR DESCRIPTION
**Pull request by robogen**
This addresses #46 

Electron offers a 'modal' dialog that I liked the features of, so I gave that a try
hccgo_modalbeta

I'm not satisfied with the color of the word 'beta', suggestions? The wording of the dialog will also need to be touched up. 

I do like doing the modal dialog like this as it is not a separate window (by that I mean clicking the application opening forces this dialog on top), by its configured properties it remains on top of the application window as long as it is open. At the same time it disables the main window; the user will have to close/interact with the modal window before they can begin interacting with the application. Later we could probably add a 'ok I've seen this, please don't pop up again' button so it doesn't appear every time.

Once inside the application the user will see this
hccgo_insidebeta

To use those electron modal features I updated to 1.4.3. At the same time I tried upgrading the packages such as d3 and c3. Found out that currently, c3 only supports version 3 of d3 at the moment. And if c3 upgrades to support version 4 of d3, the package has changed so now the newest version of d3 is actually a collection of packages and features are split across microlibraries. Doesn't affect us for now, but something to keep in mind.

### CODE REVIEW

**Comment by djw8605** [comment]
I'm not a big fan of the electron modal.  I would like something that isn't a separate window.  Just something in front of them when they start up the application.  A regular bootstrap modal should work.

**Comment by djw8605** [comment]
Also, it's ok to move the "Beta" to the right of the text.  It doesn't have to overlay the text.

**Comment by robogen** [comment]
Fair enough, I'll switch to using a bootstrap modal. Do you have text you'd like inside of it or should we stick with my filler text for now?

Would it be ok to leave the beta as overlaying? I think it looks really cool.

**Comment by djw8605** [comment]
Could you make the "Beta" text a different color?  In the pictures, the text look “blocky” (maybe low-res), could you make it a different font?  Maybe to match the rest of the application (whatever font it uses)

I like the beta overlay for the logo in the top left, but not for overlays of other text, like you had in the modal.  If it's just text, then just append "Beta".  If it's a picture, then go ahead do the overlay.

**Comment by robogen** [comment]
I can roll with that, and yes I think I agree on your 'text-over-text' point. I'll move it so instead of overlaying its 'appended' at the end.

As for color of the text over the logo, it does need to be different but I'm not 100% sure on that myself. It's the same font as the rest of the application, but I'm hard pressed to find a color that looks good near the red background and green logo.

**Comment by djw8605** [comment]
I like this as an example:
image

Black background, white text.  Small.

**Comment by robogen** [comment]
Yea, I like that too. I'll try something similar

**Comment by robogen** [comment]
This is the welcome screen now

hccgo_welcome

**Comment by robogen** [comment]
This commit puts in the html modal method, on launch users will see 

hccgo_modal

Not 100% on the content yet, so I just have filler text at the moment.

**Comment by djw8605** [comment]
The text box look good!

**Comment by robogen** [comment]
Awesome, glad you like it! The latest commit fixes the text on image in the navbar

hccgo_betanote

**Comment by djw8605** [comment]
I like it!  The new picture.

Are we done with this request then?

**Comment by robogen** [comment]
If you're satisfied with how everything looks, then yeah this should satisfy this request. The only thing will be the full contents of the modal dialog, but you can pull this into the master repo and fill that in at your leisure.

**Pull request merged**
