### PR TITLE
Electron

### PR DESCRIPTION
**Pull request by robogen**
This PR adds in the switch from using node-webkit to using electron. It doesn't do anything new really beyond what we have been doing with node-webkit, but since this makes the change to using electron for development it opens up capabilities that are specific to electron.

This also holds a fix related to the package 'diskusage' where there were build issues with node-gyp happening, and rebuilding with electron headers fixes those issues.

This also changes the grunt commands a little, and adds the auto npm build capability for the source directory, which has been renamed to HCCGo for 'electron' reasons. The default 'grunt' command builds everything and puts files where they are needed, but you have to go into the sub 'HCCGo' directory and run 'npm start' to run the application. The command 'grunt run' does that for you. The command 'grunt package' will build everything and package everything into an executable for a given system.

I have that setup, but you have to modify Gruntfile.js slightly. Where I have 'build_electron' defined, there's a command "npm run-script packageWin". If you change the 'packageWin' to 'packageOsx' it'll create a .app for your system. I have these changes documented in the README.

Also, "grunt run" will contain the development tools, but "grunt package" doesn't have them. That's not a personal design choice, just how electron-builder works by default. I did have an issue where the app worked fine with "grunt run" but I had to fix some issues when I tried to package it and run it where on the File Management page the environment variables were different, but I'm working on Windows. It shouldn't affect you, but if it does let me know.

If you like it and want to use it, I'm excited to dev with it. I saw some builtin modules for things like taskbar notifications that I'm interested in using.

### CODE REVIEW

**Comment by djw8605** [comment]
Interesting...  Lots of changes.  This is going to take some thinking...

I'm scared to change the underlying infrastructure when we haven't even released version 1.  But if this helps with building native packages, that may be reason enough.  Have you been able to build for all platforms?

**Comment by robogen** [comment]
I had to do a slight fix for linux, but I have it confirmed working on Windows and Linux right now. It has the capability for building on osx but I haven't tested that yet.

**Comment by djw8605** [comment]
Hum... I got it to work.  And everything seems to work.  And it all seems the same.  

Was there any code changes?  I noticed there where some more `require`s

**Comment by djw8605** [comment]
Also, probably have to clean up the src directory.  Should anything be left in there?

**Comment by robogen** [comment]
There were slight code changes, on https://github.com/robogen/HCCGo/blob/26f85ce660f545d20ac91562fbfd49e42c5b9018/HCCGo/app/index.html on line 10 and 11 I changed where jQuery gets pulled in and had to add an extra line of script to establish jQuery use of the $ symbol. And on https://github.com/robogen/HCCGo/blob/26f85ce660f545d20ac91562fbfd49e42c5b9018/HCCGo/app/js/PreferencesManager.js on line 15 there's an extra require to the path library and that line shows how you have to establish path strings to use config files specific to the app directory.

And no, using electron makes the 'src' directory obsolete and unnecessary, nothing is needed in there.

**Comment by djw8605** [comment]
Can you remove the src directory completely then in the pull request. 

-Derek

**Comment by robogen** [comment]
Otherwise, for right now at least, this behaves exactly how the app has always acted. This does fix it so now how you would normally have to recompile the ref and ffi modules with nw-gyp, the electron package headers fix it so they're recompiled to be used inside of electron, and automates the process so no extra actions have to be taken by the developer.

And I thought I had removed the directory? It's not part of my branch in my repo.

**Comment by djw8605** [comment]
Yeah, I removed the src directory, and it is now happy.

So, you are happy with the move to Electron?  If so, I am happy to merge this.

**Comment by robogen** [comment]
Yea, I'm happy with it! I'm excited to develop with it moving forward.

**Pull request merged**
